# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-Dispatch
version:      0.10_02
version_from: 
installdirs:  site
requires:
    mod_perl2:                     1.99023

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
